# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main, refactor_branch ]
  pull_request: {}

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-ubuntu:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 20

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
            submodules: recursive

      # Runs a set of commands using the runners shell
      - name: build volepsi
        run: |
          git clone https://github.com/Visa-Research/volepsi.git
          cd volepsi
          git checkout 687ca2dd03fd663a216b6ede9d2707f6d5b10b00
          python3 build.py -DVOLE_PSI_ENABLE_BOOST=ON -DVOLE_PSI_ENABLE_GMW=ON -DVOLE_PSI_ENABLE_CPSI=ON -DVOLE_PSI_ENABLE_OPPRF=ON
          python3 build.py --install=../libvolepsi
          cp out/build/linux/volePSI/config.h ../libvolepsi/include/volePSI/
          cd ..              
      - name: build
        run: |
          mkdir build && cd build
          cmake ..
          make
          cd ..
          
      - name: running code
        run: |
          ./build/miniMPSI -mpsi -n 10 -m 10 -t 1 -r 0